
import { Instrument, Category } from './types';

export const INSTRUMENTS: Instrument[] = [
  { id: 'grand-piano', name: 'GRAND PIANO', category: 'PIANO' },
  { id: 'bright-piano', name: 'BRIGHT PIANO', category: 'PIANO' },
  { id: 'e-grand-piano', name: 'E-GRAND PIANO', category: 'PIANO' },
  { id: 'honky-tonk', name: 'HONKY-TONK', category: 'PIANO' },
  { id: 'rhodes-piano', name: 'RHODES PIANO', category: 'KEYS' },
  { id: 'chorused-ep', name: 'CHORUSED EP', category: 'KEYS' },
  { id: 'harpsichord', name: 'HARPSICHORD', category: 'KEYS' },
  { id: 'clavinet', name: 'CLAVINET', category: 'KEYS' },
  { id: 'celesta', name: 'CELESTA', category: 'PERC' },
  { id: 'glockenspiel', name: 'GLOCKENSPIEL', category: 'PERC' },
  { id: 'vibraphone', name: 'VIBRAPHONE', category: 'PERC' },
  { id: 'marimba', name: 'MARIMBA', category: 'PERC' },
  { id: 'drawbar-organ', name: 'DRAWBAR ORGAN', category: 'ORGAN' },
  { id: 'perc-organ', name: 'PERC ORGAN', category: 'ORGAN' },
  { id: 'rock-organ', name: 'ROCK ORGAN', category: 'ORGAN' },
  { id: 'church-organ', name: 'CHURCH ORGAN', category: 'ORGAN' },
  { id: 'accordion', name: 'ACCORDION', category: 'ORGAN' },
  { id: 'nylon-guitar', name: 'NYLON GUITAR', category: 'GUITAR' },
  { id: 'steel-guitar', name: 'STEEL GUITAR', category: 'GUITAR' },
  { id: 'jazz-guitar', name: 'JAZZ GUITAR', category: 'GUITAR' },
  { id: 'clean-electric', name: 'CLEAN ELECTRIC', category: 'GUITAR' },
  { id: 'distortion-gt', name: 'DISTORTION GT', category: 'GUITAR' },
  { id: 'acoustic-bass', name: 'ACOUSTIC BASS', category: 'BASS' },
  { id: 'finger-bass', name: 'FINGER BASS', category: 'BASS' },
  { id: 'fretless-bass', name: 'FRETLESS BASS', category: 'BASS' },
  { id: 'synth-bass-1', name: 'SYNTH BASS 1', category: 'BASS' },
  { id: 'synth-bass-2', name: 'SYNTH BASS 2', category: 'BASS' },
  { id: 'violin', name: 'VIOLIN', category: 'STRINGS' },
  { id: 'viola', name: 'VIOLA', category: 'STRINGS' },
  { id: 'cello', name: 'CELLO', category: 'STRINGS' },
  { id: 'contrabass', name: 'CONTRABASS', category: 'STRINGS' },
  { id: 'pizzicato', name: 'PIZZICATO', category: 'STRINGS' },
  { id: 'strings-1', name: 'STRINGS 1', category: 'STRINGS' },
  { id: 'trumpet', name: 'TRUMPET', category: 'BRASS' },
  { id: 'trombone', name: 'TROMBONE', category: 'BRASS' },
  { id: 'tuba', name: 'TUBA', category: 'BRASS' },
  { id: 'french-horn', name: 'FRENCH HORN', category: 'BRASS' },
  { id: 'brass-section', name: 'BRASS SECTION', category: 'BRASS' },
  { id: 'soprano-sax', name: 'SOPRANO SAX', category: 'REED' },
  { id: 'alto-sax', name: 'ALTO SAX', category: 'REED' },
  { id: 'tenor-sax', name: 'TENOR SAX', category: 'REED' },
  { id: 'baritone-sax', name: 'BARITONE SAX', category: 'REED' },
  { id: 'clarinet', name: 'CLARINET', category: 'REED' },
  { id: 'flute', name: 'FLUTE', category: 'REED' },
  { id: 'pan-flute', name: 'PAN FLUTE', category: 'REED' },
  { id: 'square-lead', name: 'SQUARE LEAD', category: 'SYNTH' },
  { id: 'saw-lead', name: 'SAW LEAD', category: 'SYNTH' },
  { id: 'calliope-lead', name: 'CALLIOPE LEAD', category: 'SYNTH' },
  { id: 'warm-pad', name: 'WARM PAD', category: 'SYNTH' },
  { id: 'polysynth-pad', name: 'POLYSYNTH PAD', category: 'SYNTH' },
  { id: 'halo-pad', name: 'HALO PAD', category: 'SYNTH' },
  { id: 'sitar', name: 'SITAR', category: 'ETHNIC' },
  { id: 'banjo', name: 'BANJO', category: 'ETHNIC' },
  { id: 'shamisen', name: 'SHAMISEN', category: 'ETHNIC' },
  { id: 'kalimba', name: 'KALIMBA', category: 'ETHNIC' },
];

export const CATEGORIES = Object.values(Category);
